### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by greensky123** [BaronZ88/Blog#2]
我是看了你的安居客架构演变找到你的，我想知道你们的APP地图加载marker那块实现的思路，我看到你们加载了有10000来个marker都不会有卡顿，我使用百度地图加载300都卡的不行。从服务器上加载数据就很慢，然后渲染也会有3秒的卡顿。希望能得到您的回复。

**Comment by BaronZ88** [comment]
一方面服务端只会返回当前屏幕可见范围内的 mark 数据，另一方案划出屏幕的 mark 点 App 也会及时回收。

**Comment by BaronZ88** [comment]
> 我是看了你的安居客架构演变找到你的，我想知道你们的APP地图加载marker那块实现的思路，我看到你们加载了有10000来个marker都不会有卡顿，我使用百度地图加载300都卡的不行。从服务器上加载数据就很慢，然后渲染也会有3秒的卡顿。希望能得到您的回复。

一方面服务端只会返回当前屏幕可见范围内的 mark 数据，另一方案划出屏幕的 mark 点 App 也会及时回收。

**Comment by greensky123** [comment]
嗯，谢谢分享经验，屏幕可见范围 这个是有相关的算法么

**Comment by BaronZ88** [comment]
> 嗯，谢谢分享经验，屏幕可见范围 这个是有相关的算法么

MapSDK 里有方法能获取到屏幕四个角的经纬度的
